appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UCn1pm69PcmVP8O2ptqrpN83ER9EVBl4MV/PlHf3pf5zxydGcrbb8p8aQOduVUOjLEN299Ejndi7ZDifkC2UK5YVzJ/fpxPhMavnFVaU1ssmAuYuRmbei3W3KFOJL3SmnFWBW6eXe/crcwbgYGXAg5Qs93aA1AX0EdNIvGY2LGoUQWySIYn2v3PYFu60bPaT+k6yomF5jdDGcja0LPfkC7+o3eLy2hKahew+0XEHksFo7H3lY7EFZWp8syXoUpPVBEgMOeIa9DehELst14rf09uIqGRJ2tKdwCbrupiI5Q3zklJcpn9xVUP/akYFHdIz8fsJplp9OPOsxw/O1M3vLfRUiUzIwvrikmjnDPFcPhBEnLoHxQlC5Ro3yhocT746hGtAJ5Y1M1YafRme18G0+cxx/JDHzULGknQczVaCzfOPSFH3SUcfhGpY+JTwSQ8b2AxpKdSRIVFYi+5FCkxi5Ck+l9LUcoRoJ21MchEB8SlzoyNIXr3iJ6rcigAsjO0XnGR+WM9czGllIuFagSDjuuCw8hV9qEeIPzzRrzAO+U5Vbi7Whcao+27TVKvvzQuPE1E7wt82K2Pl3d2Zq5+D/6m/L1nCR9OauY/Mo2gGXC/b8MwhPTVs7/DXVgFH3ScRq1Xp6Gj0iW9/kdZ58lM2ZDH1wWsz/4KlzdyFBor4El8=}
provider:
  win: azure
bot:
  automerge: true
